const WORDS = [
  "alpine", "amber", "anchor", "aspen", "aurora",
  "badger", "basalt", "bay", "beacon", "bear",
  "birch", "blaze", "bloom", "bluff", "boulder",
  "bramble", "breeze", "brook", "brush", "buffalo",
  "canyon", "cardinal", "cascade", "cavern", "cedar",
  "cherry", "chestnut", "cliff", "cloud", "clover",
  "cobalt", "condor", "copper", "coral", "cove",
  "coyote", "crane", "creek", "crest", "cricket",
  "crimson", "crystal", "cypress", "dagger", "dawn",
  "deer", "delta", "desert", "dove", "dune",
  "dusk", "eagle", "earth", "elm", "ember",
  "falcon", "fern", "finch", "fir", "firefly",
  "fjord", "flame", "flint", "flower", "fog",
  "forest", "fox", "frost", "gale", "garnet",
  "glacier", "glade", "glen", "granite", "grove",
  "gull", "harbor", "hare", "hawk", "hazel",
  "heath", "hemlock", "heron", "hickory", "hill",
  "holly", "horizon", "hummingbird", "iris", "island",
  "ivy", "jade", "jasmine", "jasper", "jay",
  "juniper", "kestrel", "kingfisher", "lagoon", "lake",
  "larch", "lark", "laurel", "lava", "leaf",
  "leopard", "lichen", "lightning", "lily", "lion",
  "lotus", "lynx", "magpie", "maple", "marble",
  "marigold", "marsh", "meadow", "mesa", "mist",
  "moon", "moose", "moss", "mountain", "nectar",
  "nettle", "north", "oak", "oasis", "obsidian",
  "ocean", "olive", "onyx", "opal", "orchid",
  "oriole", "osprey", "otter", "owl", "palm",
  "panther", "peak", "pearl", "pebble", "pelican",
  "peony", "pine", "plains", "plum", "polar",
  "pond", "poplar", "poppy", "prairie", "puma",
  "quail", "quartz", "rain", "rapids", "raven",
  "redwood", "reef", "ridge", "river", "robin",
  "rock", "rose", "rowan", "ruby", "rush",
  "saffron", "sage", "salmon", "sand", "sandstone",
  "sapphire", "savanna", "scarlet", "sea", "sequoia",
  "shade", "shadow", "shore", "silver", "sky",
  "slate", "snow", "sorrel", "south", "sparrow",
  "spring", "spruce", "star", "starling", "stone",
  "stork", "storm", "stream", "summit", "sun",
  "swallow", "swan", "swift", "sycamore", "talon",
  "tamarack", "tanager", "teal", "terra", "thistle",
  "thorn", "thrush", "thunder", "tide", "tiger",
  "timber", "topaz", "trail", "trout", "tulip",
  "tundra", "twilight", "valley", "verdant", "violet",
  "viper", "walnut", "warbler", "wave", "west",
  "whale", "willow", "wind", "wisteria", "wolf",
  "wood", "wren", "yarrow", "yew", "zenith",
  "zephyr", "zinc"
];

export function generateRandomWord(): string {
  const index = Math.floor(Math.random() * WORDS.length);
  return WORDS[index];
}
